notifications:
  email: false

language: php

php:
  - 5.4
  - 5.5

before_install:
  - npm install -g grunt-cli

install:
  - bundle install
  - composer install
  - npm install

script:
  - grunt release
