notifications:
  email: false

branches:
  only:
    - master

language: php

php:
  - 5.4
  - 5.5

# @TODO set up complete WP instance
# mysql:
#   database: glutton
#   username: glutton
#   encoding: utf8

before_install:
  - npm install -g grunt-cli

install:
  - bundle install
  - composer install
  - npm install
#  - sudo apt-get install apache2 libapache2-mod-fastcgi
# # enable php-fpm
# - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
# - sudo a2enmod rewrite actions fastcgi alias
# - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
# - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
# # configure apache virtual hosts
# - sudo cp -f .travis/travis-ci-apache /etc/apache2/sites-available/default
# - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
# - sudo service apache2 restart

script:
  - grunt release

