language: node_js

node_js:
- '0.11'
- '0.10'

php:
  - 5.4
  - 5.5

before_install:
  - npm install -g grunt-cli

install:
  - composer install
  - npm install

before_script:
  - grunt build

notifications:
  email: false
