notifications:
  email: false

branches:
  only:
  - master

language: php
php:
  - 5.4
  - 5.5

before_install:
  - npm install -g grunt-cli

install:
  - bundle install
  - composer install --prefer-source --no-interaction
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g codeclimate-test-reporter

script:
  - grunt release
  - grunt coveralls
  - codeclimate < reports/coverage/PhantomJS\ 1.9.7\ \(Linux\)/lcov.info

env:
  global:
    secure: Q5OYy2ftzVvdg5LqJjPiHqze2DXwI6N8DCj0+xiRLSWypqNjIeFmKidnG948W4flXYxP+au/jsMJYPsXtiz2z5JLQL/3aOpP7ab4q1CFeD6sVqssSlU1Xkm4czFNx1OS16bn2ptKORZOD9BtBdMh2vYUaEh4flOKNA4I36Qw/Yc=
