language: php
php:
  - 5.4
  - 5.5

before_install:
  - npm install -g grunt-cli

install:
  - bundle check || bundle install
  - composer install --prefer-source --no-interaction
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - grunt release
  - grunt test

after_script:
  - grunt coveralls
  - npm install -g codeclimate-test-reporter
  - cat reports/coverage/PhantomJS\ 1.9.7\ \(Linux\)/lcov.info | codeclimate

addons:
  code_climate:
    repo_token: c33f1e5138af3deced852e0b29608c21e92269147d6262d2fc766b44e8e223a8
